### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by Slash-73** [Dominux/SD_deepnude#16]
Traceback (most recent call last):
  File "E:\test\SD_deepnude-main\bot.py", line 13, in <module>
    API_TOKEN = os.environ["API_TOKEN"]
  File "<frozen os>", line 679, in __getitem__
KeyError: 'API_TOKEN'

**Comment by Dominux** [comment]
Hey yo

I've read your comment and wanna ask you some question. Like how dumb are you? Cause you just missed some step from readme instruction
